# Generated by Django 5.2.8 on 2026-03-08 16:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US'),
        ),
    ]
